const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('vibeAPI', {
  getConfig:        ()      => ipcRenderer.invoke('get-config'),
  saveConfig:       (c)     => ipcRenderer.invoke('save-config', c),
  getLibrary:       ()      => ipcRenderer.invoke('get-library'),
  saveLibrary:      (l)     => ipcRenderer.invoke('save-library', l),
  scanFolder:       (p)     => ipcRenderer.invoke('scan-folder', p),
  scanIncremental:  (opts)  => ipcRenderer.invoke('scan-incremental', opts),
  readMetadata:     (p)     => ipcRenderer.invoke('read-metadata', p),
  readMetaBatch:    (paths) => ipcRenderer.invoke('read-meta-batch', paths),
  openFiles:        ()      => ipcRenderer.invoke('open-files'),
  openFolder:       ()      => ipcRenderer.invoke('open-folder'),
  exportPlaylist:   (d)     => ipcRenderer.invoke('export-playlist', d),
  importPlaylist:   ()      => ipcRenderer.invoke('import-playlist'),
  deleteFile:       (p)     => ipcRenderer.invoke('delete-file', p),
  pruneArtCache:    (urls)  => ipcRenderer.invoke('prune-art-cache', urls),
  notifyTrack:      (t)     => ipcRenderer.send('notify-track', t),
  onTrayAction:     (cb)    => ipcRenderer.on('tray-action',(_,a)=>cb(a)),
  onGlobalShortcut: (cb)    => ipcRenderer.on('global-shortcut',(_,a)=>cb(a)),
  windowControl:    (a)     => ipcRenderer.send('window-control', a),
  openExternal:     (url)   => ipcRenderer.send('open-external', url),
  getAudioDevices:  ()      => ipcRenderer.invoke('get-audio-devices'),
  log:              (lvl,...a) => ipcRenderer.invoke('log', lvl, ...a),
});
